name: Deploy
inputs:
  environment:
    description: Environment
    required: true
  project:
    description: Project
    required: true
  token: 
    description: Token
    required: true
outputs:
  manifest:
    description: Manifest
runs:
  using: 'node16'
  main: 'dist/index.js'
