name: Deploy
inputs:
  environment:
    description: Environment to create. It determines the workflow to be launched in the platform repository
    required: true
  project:
    description: Project to which the deploy containing the deploy action belongs
    required: true
  token: 
    description: Github token
    required: true
  repo-name:
    description: Repository containing the deploy platform workflow. Defaults to "[project]-platform"
  workflow-id:
    description: ID of the workflow to trigger. Defaults to "deploy.yml"
  ref:
    description: Ref to trigger the workflow. Defaults to "main"
outputs:
  manifest:
    description: Manifest downloaded from the deploy workflow artifact
runs:
  using: 'node16'
  main: 'dist/index.js'
