name: Write Secret
description: Write secret to Github repository or environment
inputs:
  value:
    description: Value to write to secret
    required: true
  secret:
    description: Secret name
    required: true
  repositories:
    description: Repositories to sync represented as JSON Array
    required: true
  environment:
    description: Environment to sync
    required: false
  token: 
    description: Github token
    required: true
outputs:
  manifest:
    description: Manifest with information about written secrets
runs:
  using: 'node16'
  main: 'dist/index.js'
