name: Deploy workflow for component tests

on:
  workflow_dispatch:
    inputs:
      id:
        required: true
        type: string
        description: Id for the identifier step

jobs:
  deploy:
    runs-on: ${{ vars.JOBS_RUNNER }}
    steps:
      - name: Set ID (${{github.event.inputs.id}})
        run: echo "The id of this workflow is ${{github.event.inputs.id}}"
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create fake deployment manifest
        run: |
          echo "{\"finished\":true,\"registry\":{\"server\":\"foo-server\"}}" > deployment.json
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: deployment
          path: deployment.json
          retention-days: 1
