name: Test Component

on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string
        description: 'The branch or tag ref to deploy'
    secrets:
      GITHUB_TOKEN:
        required: true

jobs: 
  test-component-deploy:
    runs-on: ${{ vars.JOBS_RUNNER }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - id: deploy
        name: Launch deploy action
        uses: ./deploy-platform
        with:
          environment: 'test'
          project: 'cross-platform-actions'
          repo-name: 'cross-platform-actions'
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ inputs.ref }}
          request-interval: 5000
      - name: Check deployment manifest
        run: |
          echo '${{ steps.deploy.outputs.manifest }}' | jq -r '.registry.server' | grep 'foo-server' || (echo "Manifest is wrong" && exit 1)

      
      