name: Test

on:
  push:
    branches:
      - CROSS-499/test/e2e

jobs:
  test-e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Launch deploy action
        uses: ./
        with:
          environment: 'foo-environment'
          project: 'cross-platform-actions'
          repo-suffix: ''
          token: ${{ secrets.GITHUB_TOKEN }}
          workflow-id: 'deploy-test.yml'
          ref: ${{ github.head_ref || github.ref_name }}
