name: Test Component

on:
  workflow_call:
    secrets:
      TOKEN:
        description: 'Token to access the repository'
        required: true

jobs:
  test-component-deploy:
    runs-on: ${{ vars.JOBS_RUNNER }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - id: deploy
        name: Launch deploy action
        uses: ./deploy-platform
        with:
          environment: "test"
          project: "cross-platform-actions"
          repo-name: "cross-platform-actions"
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.head_ref || github.ref_name }}
          request-interval: 5000
      - name: Check deployment manifest
        run: |
          echo '${{ steps.deploy.outputs.manifest }}' | jq -r '.registry.server' | grep 'foo-server' || (echo "Manifest is wrong" && exit 1)
  test-component-write-env-secret:
    runs-on: ${{ vars.JOBS_RUNNER }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - id: write-env-secret
        name: Launch write-env-secret action
        uses: ./write-env-secret
        with:
          secret: EXAMPLE_SECRET_NAME
          value: |
            {"example": "manifest"}
          repositories: |
            [ "Telefonica/cross-platform-actions" ]
          token: ${{ secrets.TOKEN }}
      - name: Check write-env-secret manifest
        run: |
          [[ -z "${{ secrets.EXAMPLE_SECRET_NAME }}" ]] && (echo "::error::Secret is not set" && exit 1)
