name: Test

on:
  push:
    branches:
      - main
      - release/*
  pull_request:

jobs:
  check:
    runs-on: ${{ vars.JOBS_RUNNER }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup env
        uses: ./.github/actions/pnpm-install
      - name: Lint
        run: pnpm run lint
      - name: Check spelling
        run: pnpm run check:spelling
      - name: Check Types
        run: pnpm nx run-many -t check:types
  test-unit:
    runs-on: ${{ vars.JOBS_RUNNER }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup env
        uses: ./.github/actions/pnpm-install
      - name: Test
        run: pnpm nx run-many -t test
  build:
    runs-on: ${{ vars.JOBS_RUNNER }}
    defaults:
      run:
        working-directory: deploy-platform
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup env
        uses: ./.github/actions/pnpm-install
      - name: Build
        run: pnpm nx run-many --skip-nx-cache -t build
      - name: Check dist (deploy-platform)
        id: diff-deploy-platform
        working-directory: deploy-platform
        run: |
          pnpm nx run-many -t check:dist
  test-component:
    uses: ./.github/workflows/test-component.yml
    needs: build
    secrets:
      WRITE_SECRET_PAT: ${{ secrets.PAT_SYNC_MANIFEST_CROSS_1455 }}
